// This code was autogenerated from nevent, do not edit.
package proto

import (
	"context"
	"fmt"

	"github.com/LilithGames/nevent"
	pb "github.com/LilithGames/nevent/proto"
	"github.com/golang/protobuf/proto"
	"github.com/nats-io/nats.go"
)
