// This code was autogenerated from nevent, do not edit.
package proto

import (
	"context"

	"github.com/LilithGames/nevent"
	"google.golang.org/grpc/metadata"
	"github.com/golang/protobuf/ptypes"
	pb "github.com/LilithGames/nevent/proto"
)

type PersonEventListener interface {
	OnPersonEvent(ctx context.Context, e *Person)
	OnError(err error)
}

func RegisterPersonEvent(s *nevent.Server, handler PersonEventListener, opts ...nevent.ListenOption) {
	cb := func(subject string, reply string, e *pb.Event) {
		data := new(Person)
		err := ptypes.UnmarshalAny(e.Data, data)
		if err != nil {
			handler.OnError(err)
			return
		}
		ctx := metadata.NewIncomingContext(context.TODO(), nevent.MDFromEvent(e))
		s.GetInterceptor()(ctx, subject, reply, data)
		handler.OnPersonEvent(ctx, data)
	}
	s.ListenEvent("test.persion", cb, opts...)
}

func EmitPerson(ctx context.Context, nc *nevent.Client, e *Person, opts ...nevent.EmitOption) error {
	nc.GetInterceptor()(ctx, "test.persion", "emit", e)
	data, err := ptypes.MarshalAny(e)
	if err != nil {
		return err
	}
	md, _ := metadata.FromOutgoingContext(ctx)
	return nc.Emit("test.persion", nevent.NewEvent(md, data), opts...)
}

func (it *Person)Emit(ctx context.Context, nc *nevent.Client, opts ...nevent.EmitOption) error {
	return EmitPerson(ctx, nc, it, opts...)
}


